enableGlobalCache: false
nodeLinker: pnp

# plugins:
#   - checksum: af54e2b651227900c9f89cfffd4bc14cea30c3db317a72ab71ab89bdd9f21922b7b7555cbf7785ae15da052ecce220e7a117b1a8911a07aa8a58cc1c7b77316c
#     path: .yarn/plugins/plugin-auto-workspace-deps.cjs
#     spec: auto-workspace-deps.js
# pnpFallbackMode: all
plugins:
  - .yarn/plugins/plugin-add-both.js
pnpMode: strict
supportedArchitectures:
  cpu:
    - arm64
  os:
    - darwin
    - linux
packageExtensions:
  'eslint-config-airbnb-typescript@*':
    peerDependencies:
      'eslint-plugin-import': '*'
  # 'express@*':
  #   peerDependencies:
  #     'pug': '*'
  '@typescript-eslint/utils@*':
    peerDependencies:
      'typescript': '*'
  '@typescript-eslint/typescript-estree@*':
    peerDependencies:
      'typescript': '*'
  '@types/connect-mongo@*':
    peerDependencies:
      'mongodb': '*'
      'express-session': '*'
  '@swc-node/register@*':
    peerDependencies:
      '@swc/types': '*'
  # '@module-federation/enhanced@*':
  #   peerDependencies:
  #     'typescript': '*'
  # '@nx/webpack@*':
  #   peerDependencies:
  #     'typescript': '*'
  #     'nx': '*'
  # '@nx/web@*':
  #   peerDependencies:
  #     'typescript': '*'
  #     'nx': '*'
  # '@nx/react@*':
  #   peerDependencies:
  #     'typescript': '*'
  #     'nx': '*'
  #     'eslint': '*'
  # '@nx/node@*':
  #   peerDependencies:
  #     'typescript': '*'
  #     'nx': '*'
  #     'eslint': '*'
  # '@nx/next@*':
  #   peerDependencies:
  #     'typescript': '*'
  #     'nx': '*'
  #     'eslint': '*'
  # '@nx/linter@*':
  #   peerDependencies:
  #     'eslint': '*'
  # '@nx/js@*':
  #   peerDependencies:
  #     'nx': '*'
