enableGlobalCache: false
nodeLinker: pnp
compressionLevel: 7
pnpMode: strict
supportedArchitectures:
  cpu:
    - arm64
  os:
    - darwin
    - linux
packageExtensions:
  'eslint-config-airbnb-typescript@*':
    peerDependencies:
      'eslint-plugin-import': '*'
  '@typescript-eslint/utils@*':
    peerDependencies:
      'typescript': '*'
  '@typescript-eslint/typescript-estree@*':
    peerDependencies:
      'typescript': '*'
  '@types/connect-mongo@*':
    peerDependencies:
      'mongodb': '*'
      'express-session': '*'
  '@swc-node/register@*':
    peerDependencies:
      '@swc/types': '*'
  # '@module-federation/enhanced@*':
  #   peerDependencies:
  #     'typescript': '*'
  # '@nx/webpack@*':
  #   peerDependencies:
  #     'typescript': '*'
  #     'nx': '*'
  # '@nx/web@*':
  #   peerDependencies:
  #     'typescript': '*'
  #     'nx': '*'
  # '@nx/react@*':
  #   peerDependencies:
  #     'typescript': '*'
  #     'nx': '*'
  #     'eslint': '*'
  # '@nx/node@*':
  #   peerDependencies:
  #     'typescript': '*'
  #     'nx': '*'
  #     'eslint': '*'
  # '@nx/next@*':
  #   peerDependencies:
  #     'typescript': '*'
  #     'nx': '*'
  #     'eslint': '*'
  # '@nx/linter@*':
  #   peerDependencies:
  #     'eslint': '*'
  # '@nx/js@*':
  #   peerDependencies:
  #     'nx': '*'
