enableGlobalCache: false
nodeLinker: pnp
pnpMode: strict
supportedArchitectures:
  cpu:
    - x64
    - arm64
  os:
    - windows
    - darwin
    - linux
packageExtensions:
  "@swc-node/register@*":
    peerDependencies:
      "@swc/types": "*"
  "@types/connect-mongo@*":
    peerDependencies:
      express-session: "*"
      mongodb: "*"
  "@typescript-eslint/typescript-estree@*":
    peerDependencies:
      typescript: "*"
  "@typescript-eslint/utils@*":
    peerDependencies:
      typescript: "*"
  eslint-config-airbnb-typescript@*:
    peerDependencies:
      eslint-plugin-import: "*"


