version: '3.8'

services:
  smpark-space:
    build:
      context: ../../
      dockerfile: apps/smpark-space/Dockerfile
      target: production
    image: smpark9596/smpark-space:${VERSION}
    platform: linux/amd64
    container_name: smpark-space-${VERSION}
    ports:
      - "3000:3000"
    env_file:
      - .env.production
    environment:
      - NODE_ENV=production
      
    command: yarn smpark-space:prod

networks:
  default:
    name: smpark-space-network-prod