version: '3.8'

services:
  smpark-space:
    build:
      context: ../../
      dockerfile: apps/smpark-space/Dockerfile
      target: production
    image: smpark9596/smpark_space:${SPACE_VERSION}
    container_name: smpark_space_${SPACE_VERSION}
    ports:
      - "3000:3000"
    env_file:
      - .env.production
    environment:
      - NODE_ENV=production
    command: yarn smpark_space:prod

networks:
  default:
    name: smpark_space_network_prod