version: '3.8'

services:
  smpark-oauth2.0:
    build:
      context: ../../
      dockerfile: apps/smpark-oauth2.0/Dockerfile
      target: production
    image: smpark9596/oauth2.0:${VERSION}
    container_name: oauth2.0_${VERSION}
    ports:
      - '3333:5555'
    env_file:
      - .env.production
    environment:
      - NODE_ENV=production
    volumes:
      - smpark-log:/usr/src/oauth-log
    command: yarn oauth2.0:prod

networks:
  default:
    name: smpark_oauth_network_prod

volumes:
  smpark-log:
