version: '3.8'

services:
  smpark-oauth2.0:
    build:
      context: ../../
      dockerfile: apps/smpark-oauth2.0/Dockerfile
      target: production
    image: smpark9596/smpark-oauth2.0:${VERSION}
    platform: linux/amd64
    container_name: smpark-oauth2.0-${VERSION}
    ports:
      - '4444:4000'
    env_file:
      - .env.production
    environment:
      - NODE_ENV=production
    volumes:
      - oauth-log:/usr/src/oauth-log
    command: yarn smpark-oauth2.0:prod

networks:
  default:
    name: smpark-oauth-network-prod

volumes:
  oauth-log:
