version: '3.8'

services:
  smpark-oauth2.0:
    build:
      context: ../../
      dockerfile: apps/smpark-oauth2.0/Dockerfile
      target: production
    image: smpark9596/smpark-oauth2.0:${VERSION}
    platform: linux/amd64
    container_name: smpark-oauth2.0
    ports:
      - '4444:4000'
    env_file:
      - .env.production
    environment:
      - NODE_ENV=production
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
    volumes:
      - oauth-log:/usr/src/oauth-log
    command: yarn smpark-oauth2.0:prod
    networks:
      - smpark-oauth-network-prod 

  redis:
    image: redis:alpine
    volumes:
      - redis-data:/data
    networks:
      - smpark-oauth-network-prod

networks:
  smpark-oauth-network-prod:
    name: smpark-oauth-network-prod

volumes:
  oauth-log:
  redis-data: