version: '3.8'

services:
  smpark-resource:
    build:
      context: .
      target: development
    image: smpark9596/resource:${RESOURCE_VERSION}
    container_name: resource-dev_${RESOURCE_VERSION}
    ports:
      - '5005:5005'
    env_file:
      - .env.development
    environment:
      - NODE_ENV=development
    volumes:
    - .:/usr/src/resource
    - smpark_log:/usr/src/resource_log
    command: yarn dev
    
networks:
  default:
    name: smpark_resource_network_dev

volumes:
  smpark_log:
