name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup:
    runs-on: self-hosted
    outputs:
      affected: ${{ steps.set-affected.outputs.affected }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20.14.0
      - name: Enable Corepack
        run: corepack enable
      - uses: nrwl/nx-set-shas@v4
      - id: set-affected
        run: |
          affected=$(yarn nx show projects --type app --affected --json)
          echo "affected=$affected" >> $GITHUB_OUTPUT
  build:
    needs: setup
    if: needs.setup.outputs.affected != '[]'
    runs-on: self-hosted
    strategy:
      matrix:
        project: ${{ fromJson(needs.setup.outputs.affected) }}
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Cache LFS
        if: matrix.project == 'smpark-space'
        uses: actions/cache@v4
        with:
          path: .git/lfs/objects
          key: ${{ runner.os }}-lfs-${{ hashFiles('.gitattributes') }}
          restore-keys: |
            ${{ runner.os }}-lfs-
      - name: Cache Next.js
        if: matrix.project == 'smpark-space'
        uses: actions/cache@v4
        with:
          path: apps/smpark-space/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}-${{ hashFiles('apps/smpark-space/**.[jt]s', 'apps/smpark-space/**.[jt]sx') }}
      - name: Cache NX
        uses: actions/cache@v4
        with:
          path: .nx-cache
          key: ${{ runner.os }}-nx-${{ hashFiles('**/yarn.lock') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          restore-keys: |
            ${{ runner.os }}-nx-
      - name: Lint
        run: yarn nx lint ${{ matrix.project }}
      - name: Build
        run: yarn nx build:prod ${{ matrix.project }}
      - name: Deploy to Windows Desktop
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_NOIP_HOSTNAME }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            eploy.bat "${{ secrets.DOCKER_USERNAME }}" "${{ secrets.DOCKER_TOKEN }}" "${{ matrix.project }}" "${{ vars.OAUTH_VERSION }}" "${{ vars.SPACE_VERSION }}" "${{ vars.NODE_ENV }}" "${{ secrets.LOGIN_EXPIRES_IN }}" "${{ secrets.LOGIN_JWT_SECRET_KEY }}" "${{ secrets.MONGO_DATABASE_NAME }}" "${{ secrets.MONGO_DATABASE_PASSWORD }}" "${{ secrets.MONGO_DATABASE_SESSION_COLLECTION }}" "${{ secrets.MONGO_DATABASE_SESSION_KEY }}" "${{ secrets.MONGO_DATABASE_URI }}" "${{ secrets.MONGO_DATABASE_USER }}" "${{ secrets.OAUTH_ACCESS_SECRET_KEY }}" "${{ secrets.OAUTH_ACCESS_TOKEN_EXPIRES_IN }}" "${{ secrets.OAUTH_CODE_EXPIRES_IN }}" "${{ secrets.OAUTH_REFRESH_SECRET_KEY }}" "${{ secrets.OAUTH_REFRESH_TOKEN_EXPIRES_IN }}" "${{ vars.OAUTH_ISSUER }}" "${{ vars.NGINX_PORT }}" "${{ vars.APP_PORT }}" "${{ secrets.SPACE_GOOGLE_CLIENT_ID }}" "${{ secrets.SPACE_GOOGLE_CLIENT_SECRET }}" "${{ secrets.SPACE_GITHUB_CLIENT_ID }}" "${{ secrets.SPACE_GITHUB_CLIENT_SECRET }}" "${{ secrets.SPACE_SMPARK_CLIENT_ID }}" "${{ secrets.SPACE_SMPARK_CLIENT_SECRET }}" "${{ secrets.SPACE_NEXTAUTH_SECRET }}" "${{ vars.NEXT_PUBLIC_API_URL }}" "${{ vars.SMPARK_OAUTH_BASE_URI }}" "${{ vars.SMPARK_RESOURCE_BASE_URI }}" "${{ vars.SMPARK_CLIENT_REDIRECT_URI }}"
