name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: write
  pages: write
  id-token: write


jobs:
  main:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
    
      - uses: actions/setup-node@v4
        with:
          node-version: 20.14.0
      
      - uses: nrwl/nx-set-shas@v4
      
      - name: Enable Corepack
        run: corepack enable
        

      - name: Create environment file
        run: |
          cat << EOF > apps/smpark-oauth2.0/.env.${{ vars.NODE_ENV }}
          LOGIN_EXPIRES_IN=${{ secrets.LOGIN_EXPIRES_IN }}
          LOGIN_JWT_SECRET_KEY=${{ secrets.LOGIN_JWT_SECRET_KEY }}
          MONGO_DATABASE_NAME=${{ secrets.MONGO_DATABASE_NAME }}
          MONGO_DATABASE_PASSWORD=${{ secrets.MONGO_DATABASE_PASSWORD }}
          MONGO_DATABASE_SESSION_COLLECTION=${{ secrets.MONGO_DATABASE_SESSION_COLLECTION }}
          MONGO_DATABASE_SESSION_KEY=${{ secrets.MONGO_DATABASE_SESSION_KEY }}
          MONGO_DATABASE_URI=${{ secrets.MONGO_DATABASE_URI }}
          MONGO_DATABASE_USER=${{ secrets.MONGO_DATABASE_USER }}
          OAUTH_ACCESS_SECRET_KEY=${{ secrets.OAUTH_ACCESS_SECRET_KEY }}
          OAUTH_ACCESS_TOKEN_EXPIRES_IN=${{ secrets.OAUTH_ACCESS_TOKEN_EXPIRES_IN }}
          OAUTH_CODE_EXPIRES_IN=${{ secrets.OAUTH_CODE_EXPIRES_IN }}
          OAUTH_REFRESH_SECRET_KEY=${{ secrets.OAUTH_REFRESH_SECRET_KEY }}
          OAUTH_REFRESH_TOKEN_EXPIRES_IN=${{ secrets.OAUTH_REFRESH_TOKEN_EXPIRES_IN }}
          NODE_ENV=${{ vars.NODE_ENV }}
          OAUTH_ISSUER=${{ vars.OAUTH_ISSUER }}
          NGINX_PORT=${{ vars.NGINX_PORT }}
          APP_PORT=${{ vars.APP_PORT }}
          OAUTH_VERSION=${{ vars.OAUTH_VERSION }}
          EOF

      - name: Display environment file (for debugging)
        run: |
            echo "Contents of .env.${{ vars.NODE_ENV }}:"
            cat .env.${{ vars.NODE_ENV }} | sed 's/^/  /'
      
      - name: Restore Cache
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/apps/smpark-space/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-

      - run: yarn nx affected -t build:prod