name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  main:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - uses: actions/setup-node@v4
        with:
          node-version: 20.14.0
      
      - uses: nrwl/nx-set-shas@v4
      
      - name: Corepack 활성화
        run: corepack enable

      - name: 영향받은 프로젝트 확인
        id: affected
        run: |
          affected=$(yarn nx print-affected --select=projects)
          echo "영향받은 프로젝트: $affected"
          echo "affected=$affected" >> $GITHUB_OUTPUT

      - name: 영향받은 프로젝트에 대한 환경 변수 파일 생성
        run: |
          affected_projects=${{ steps.affected.outputs.affected }}
          if echo "$affected_projects" | grep -q "space"; then
            echo "space 프로젝트에 대한 환경 변수 파일 생성"
            cat << EOF > apps/space/.env.${{ vars.NODE_ENV }}
            # space 프로젝트에 필요한 환경 변수들
            EOF
          fi
          if echo "$affected_projects" | grep -q "oauth2.0"; then
            echo "oauth2.0 프로젝트에 대한 환경 변수 파일 생성"
            cat << EOF > apps/smpark-oauth2.0/.env.${{ vars.NODE_ENV }}
            LOGIN_EXPIRES_IN=${{ secrets.LOGIN_EXPIRES_IN }}
            LOGIN_JWT_SECRET_KEY=${{ secrets.LOGIN_JWT_SECRET_KEY }}
            MONGO_DATABASE_NAME=${{ secrets.MONGO_DATABASE_NAME }}
            MONGO_DATABASE_PASSWORD=${{ secrets.MONGO_DATABASE_PASSWORD }}
            MONGO_DATABASE_SESSION_COLLECTION=${{ secrets.MONGO_DATABASE_SESSION_COLLECTION }}
            MONGO_DATABASE_SESSION_KEY=${{ secrets.MONGO_DATABASE_SESSION_KEY }}
            MONGO_DATABASE_URI=${{ secrets.MONGO_DATABASE_URI }}
            MONGO_DATABASE_USER=${{ secrets.MONGO_DATABASE_USER }}
            OAUTH_ACCESS_SECRET_KEY=${{ secrets.OAUTH_ACCESS_SECRET_KEY }}
            OAUTH_ACCESS_TOKEN_EXPIRES_IN=${{ secrets.OAUTH_ACCESS_TOKEN_EXPIRES_IN }}
            OAUTH_CODE_EXPIRES_IN=${{ secrets.OAUTH_CODE_EXPIRES_IN }}
            OAUTH_REFRESH_SECRET_KEY=${{ secrets.OAUTH_REFRESH_SECRET_KEY }}
            OAUTH_REFRESH_TOKEN_EXPIRES_IN=${{ secrets.OAUTH_REFRESH_TOKEN_EXPIRES_IN }}
            NODE_ENV=${{ vars.NODE_ENV }}
            OAUTH_ISSUER=${{ vars.OAUTH_ISSUER }}
            NGINX_PORT=${{ vars.NGINX_PORT }}
            APP_PORT=${{ vars.APP_PORT }}
            OAUTH_VERSION=${{ vars.OAUTH_VERSION }}
            EOF
          fi

      - name: 환경 변수 파일 내용 표시 (디버깅용)
        run: |
          if [ -f apps/space/.env.${{ vars.NODE_ENV }} ]; then
            echo "space .env.${{ vars.NODE_ENV }} 파일 내용:"
            cat apps/space/.env.${{ vars.NODE_ENV }} | sed 's/^/  /'
          fi
          if [ -f apps/smpark-oauth2.0/.env.${{ vars.NODE_ENV }} ]; then
            echo "oauth2.0 .env.${{ vars.NODE_ENV }} 파일 내용:"
            cat apps/smpark-oauth2.0/.env.${{ vars.NODE_ENV }} | sed 's/^/  /'
          fi

      - run: yarn nx affected -t build:prod